### ISSUE TITLE
NullPointerException in RabbitMQMonitoringTask.printMetric

### ISSUE THREAD

**Issue by stefansiegl** [Appdynamics/rabbitmq-monitoring-extension#13]
Hi guys,

We encountered a Nullpointer Exception in RabbitMQMonitoringTask.printMetric. See the following log output.

![image](https://user-images.githubusercontent.com/6985983/33705012-f73eeaa0-db2e-11e7-8ace-d39b8c7ab19b.png)

I had a look and it seems as if a null check is actually missing. I will provide a pull request for this.

Cheers,
Stefan

**Comment by satish-m** [comment]
Hi @stefansiegl ,

Thanks for reporting. Can you please tell us what version of the extension you are using? 
Also it would be great if you can create a [helpdesk](https://appdynamics.zendesk.com) ticket with the logs.

Thanks,
Satish M

**Comment by satish-m** [comment]
Thanks for creating the helpdesk ticket.

**Comment by stefansiegl** [comment]
Hi @satish-m,

I used the latest version of the plugin (HEAD). I already asked my collegues that ran the plugin for the logs but did not get them so far.

Cheers,
Stefan
