### ISSUE TITLE
Wrong Config Value

### ISSUE THREAD

**Issue by ciuliano** [Appdynamics/rabbitmq-monitoring-extension#16]
https://github.com/Appdynamics/rabbitmq-monitoring-extension/blob/4f0f0464a3273d2bc4dbb392918000459ca6f7ab/src/main/java/com/appdynamics/extensions/rabbitmq/RabbitMQMonitor.java#L176

**Comment by kunalgupApDx** [comment]
@akshayAppd @satish-m Can you please review this?

**Comment by akshayAppd** [comment]
This issue has been resolved in the latest version.
