### ISSUE TITLE
Did not publish to controller until I removed spaces from metricPrefix

### ISSUE THREAD

**Issue by kfreem02** [Appdynamics/rabbitmq-monitoring-extension#18]
The AppDynamics support team advised me to remove spaces around the pipe characters in metricPrefix.  Please update the example config to remove those spaces.
Original: metricPrefix: Custom Metrics | RabbitMQ |
Working: metricPrefix: Custom Metrics|RabbitMQ|

**Comment by russpenska** [comment]
Can confirm that this is an issue - we hit exactly the same problem.
README just needs to be updated as above.

**Comment by akshayAppd** [comment]
We faced this issue on some versions of Controller, and have fixed the metricPrefix. With latest release, all the spaces have been removed and you should not face this issue anymore
