### ISSUE TITLE
How to run the project?

### ISSUE THREAD

**Issue by fekisee** [Appdynamics/rabbitmq-monitoring-extension#5]
How to run the project?

**Comment by kunalgupApDx** [comment]
Hi,

You can either download the extension directly from https://www.appdynamics.com/community/exchange/extension/rabbitmq-monitoring-extension/

Or if you want to build it from the source then 

1. git clone the extension. 
2. cd rabbitmq-monitoring-extension && mvn clean install
3. cd target
    You will find the zipped extension.

Feel free to open a ticket at help@appdynamics.com for any further help.

Thanks
Kunal
